version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spaced_repetition_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/spaced_repetition_db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-changeme}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data:


