"""Remove complexity

Revision ID: 43db20b1b997
Revises: ae7ab5c6726b
Create Date: 2026-01-13 14:48:07.451744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43db20b1b997'
down_revision = 'ae7ab5c6726b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_words', 'last_reviewed_at')
    op.drop_column('user_words', 'total_reviews')
    op.drop_column('user_words', 'correct_reviews')
    op.drop_column('words', 'difficulty_level')
    op.drop_column('words', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('words', sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_words', sa.Column('correct_reviews', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_words', sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_words', sa.Column('last_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

