"""create courses and lessons table

Revision ID: 68044737afb5
Revises: 76a812b0faf0
Create Date: 2025-10-09 17:59:38.411783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68044737afb5'
down_revision = '76a812b0faf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

