"""add user streak fields

Revision ID: ae7ab5c6726b
Revises: 3dc8f885d836
Create Date: 2025-10-16 12:43:20.542124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7ab5c6726b'
down_revision = '3dc8f885d836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###

